"""Caption blocks into ASS (architecture.md §6.2).

Two renderers over one spec, chosen by `profile.captions.kinetic`. §6.2 said this
phase would change no schema, invalidate no golden spec and need no migration,
and it does not: `CaptionBlock` has carried per-word timings since phase 1
because `align` produces them anyway, and the only new field is on the
`RenderProfile`, which says how a job is drawn rather than what it is.

The plain renderer emits one timed block per caption. The kinetic one emits one
event per *active-word window* — the same block, the same line breaks, one word
lit — because that is the thing a viewer can follow at a short's pace.

Colour is the only channel either renderer uses, and that is a constraint rather
than a preference: an override that changed weight or scale would change glyph
advance, the line would re-wrap under the highlight, and a caption that reflows
on every word is worse than one that never moves. A five-second `lavfi` render
confirmed libass leaves the ink bounding box identical across a mid-line `\\1c`
(the mechanism check `next-phase` asks for); anything that fails that test does
not belong in here.

Geometry is per profile. Caption Y in vertical is a different number from caption
Y in widescreen, and the box is expressed in normalized output coordinates so the
same spec produces a correctly placed caption in both.
"""

from __future__ import annotations

from spec.profiles import RenderProfile

from compile.timeline import EditedCaption, EditedWord

BASE_COLOUR = "FFFFFF"
"""The style's own primary colour, as `BBGGRR`.

Written once and used twice — in the style line and in the tag that ends a
coloured run — because a reset that disagreed with the style would leave every
word after the first highlight a shade off, and only on the profiles that use a
highlight. `\\r` would avoid the duplication and reset the positional tags with
it, which is the more expensive way to be wrong."""

ACTIVE_COLOUR = "00D7FF"
"""The word being spoken, in kinetic mode. Amber against white."""

EMPHASIS_COLOUR = "F0C890"
"""A word `emphasis` marked (§7.1). A second hue rather than a second use of
`ACTIVE_COLOUR`, because the two say different things and are on screen at the
same time: the active word moves with the speech and an emphasized one does not.

This is the first thing that renders `Word.emphasis` at all. The stage has
written it since phase 9 and `compile` has projected it into `EditedWord` since
phase 2, and no pixel depended on it — a model stage whose output was invisible,
which is the same shape of finding as a check that never fires."""

ASS_HEADER = """[Script Info]
; Generated by screencut compile. Do not edit; edit the spec and re-render.
ScriptType: v4.00+
PlayResX: {width}
PlayResY: {height}
WrapStyle: 2
ScaledBorderAndShadow: yes
YCbCr Matrix: TV.709

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Caption,{font},{size},&H00{primary},&H000000FF,&H00101010,&HB4101010,-1,0,0,0,100,100,0,0,3,{pad},0,5,0,0,0,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""


def render_ass(captions: list[EditedCaption], profile: RenderProfile) -> str:
    """The whole subtitle file, as text. Deterministic — §11 hashes renders."""
    style = profile.captions
    size = max(int(round(style.type_scale * profile.height)), 8)
    # BorderStyle 3 draws an opaque box behind the text rather than an outline
    # around it, which is what keeps captions legible over a screen recording
    # where the background is arbitrary and often white.
    pad = max(int(round(size * 0.22)), 2)
    lines = [
        ASS_HEADER.format(
            width=profile.width,
            height=profile.height,
            font=style.font_family,
            size=size,
            pad=pad,
            primary=BASE_COLOUR,
        )
    ]
    x = int(round((style.box.x + style.box.w / 2) * profile.width))
    y = int(round((style.box.y + style.box.h / 2) * profile.height))
    for caption in captions:
        for t_in, t_out, active in _windows(caption, style.kinetic):
            lines.extend(
                _event(t_in, t_out, _text(caption.words, style.max_chars_per_line, active), x, y)
            )
    return "".join(lines)


def _windows(caption: EditedCaption, kinetic: bool) -> list[tuple[float, float, int | None]]:
    r"""The block's time, cut into spans that each name the word that is lit.

    Plain mode is the degenerate case — one span, nothing lit — rather than a
    second code path, so the two renderers cannot disagree about where a block
    starts and ends.

    A word stays lit until the *next* one begins rather than going dark when it
    ends. The gaps between spoken words are tens of milliseconds and
    de-highlighting across them strobes; this also means the last word is lit
    through whatever `_hold_minimum` (compile/timeline.py) added to a block a cut
    left too short to read, instead of the block hanging there with nothing lit.
    """
    lo, hi = caption.t_in, caption.t_out
    if not kinetic:
        return [(lo, hi, None)]

    words = caption.words
    spans: list[tuple[float, float, int | None]] = []
    # Only when the block starts before its first word. It normally does not —
    # `project` sets `t_in` from that word — so this is the guard rather than the
    # common case, and an empty span is dropped in `_event` regardless.
    if words[0].t_in > lo:
        spans.append((lo, words[0].t_in, None))
    for index, word in enumerate(words):
        end = words[index + 1].t_in if index + 1 < len(words) else hi
        spans.append((word.t_in, end, index))
    return [(_clamp(s, lo, hi), _clamp(e, lo, hi), active) for s, e, active in spans]


def _clamp(t: float, lo: float, hi: float) -> float:
    return max(lo, min(t, hi))


def _event(t_in: float, t_out: float, text: str, x: int, y: int) -> list[str]:
    r"""One `Dialogue` line, or none where the span has no time in it.

    Decided on the *rendered* timestamps rather than on the floats, because
    centiseconds are the space these times live in: two boundaries 4ms apart are
    a real span in Python and the same instant in the file, and libass given
    `start == end` draws a one-frame flicker or nothing at all. The spans are
    contiguous, so dropping one leaves its neighbours meeting at the timestamp it
    printed — the caption has no gap, it just never lights that word.

    Same remedy as the safe area's pixels (AGENTS.md): compare in the units the
    thing actually happens in.
    """
    start, end = timestamp(t_in), timestamp(t_out)
    if start == end:
        return []
    return [f"Dialogue: 0,{start},{end},Caption,,0,0,0,,{{\\pos({x},{y})}}{text}\n"]


def _text(words: list[EditedWord], max_chars: int, active: int | None) -> str:
    r"""The block's text with its `\N` breaks, one word optionally lit."""
    tokens = [word.text for word in words]
    return "\\N".join(
        " ".join(_token(tokens[i], _colour(words[i], i == active)) for i in line)
        for line in wrap_indices(tokens, max_chars)
    )


def _colour(word: EditedWord, is_active: bool) -> str | None:
    # Active beats emphasis for the moment it is active. A word that is both is
    # the one the viewer is being asked to read right now, and letting emphasis
    # win would make that word the only one in the block that never lights up.
    if is_active:
        return ACTIVE_COLOUR
    return EMPHASIS_COLOUR if word.emphasis else None


def _token(text: str, colour: str | None) -> str:
    if colour is None:
        return text
    return f"{{\\1c&H{colour}&}}{text}{{\\1c&H{BASE_COLOUR}&}}"


def wrap_indices(words: list[str], max_chars: int) -> list[list[int]]:
    r"""Greedy wrap, as the word indices making up each line.

    Indices rather than joined text, because the kinetic renderer has to decorate
    one word and leave every other character exactly where the plain renderer put
    it. Two wrappers — one over a string, one over words — is "one formula
    written twice" (AGENTS.md), and the copy that goes stale is always the one
    nobody is looking at. So this is the rule, and `wrap` is this joined back up.

    Greedy rather than balanced on purpose: it is what a reader can predict from
    the caption itself, and `WrapStyle: 2` means libass does no wrapping of its
    own, so what this decides is exactly what appears.
    """
    if not words:
        return []
    lines = [[0]]
    width = len(words[0])
    for index in range(1, len(words)):
        if width + 1 + len(words[index]) <= max_chars:
            lines[-1].append(index)
            width += 1 + len(words[index])
        else:
            lines.append([index])
            width = len(words[index])
    return lines


def wrap(text: str, max_chars: int) -> str:
    r"""Greedy wrap into ASS `\N` lines."""
    words = text.split()
    return "\\N".join(" ".join(words[i] for i in line) for line in wrap_indices(words, max_chars))


def timestamp(seconds: float) -> str:
    """ASS wants `H:MM:SS.cc`, and centisecond truncation is all the format has."""
    seconds = max(seconds, 0.0)
    hours, rest = divmod(int(seconds), 3600)
    minutes, secs = divmod(rest, 60)
    centis = int(round((seconds - int(seconds)) * 100))
    if centis == 100:  # rounding up a whole second must carry, not print ".100"
        centis = 0
        secs += 1
        if secs == 60:
            secs = 0
            minutes += 1
            if minutes == 60:
                minutes = 0
                hours += 1
    return f"{hours}:{minutes:02d}:{secs:02d}.{centis:02d}"


def line_count(caption: EditedCaption, profile: RenderProfile) -> int:
    return len(wrap_indices([w.text for w in caption.words], profile.captions.max_chars_per_line))
