"""Caption blocks into ASS (architecture.md §6.2).

The first compiler renders plain timed blocks and **ignores the word array**, as
§6.2 says it should. The words are carried anyway — `align` produces them, the
time projection already uses them to trim a block at a cut, and kinetic
word-highlight rendering later is a change to this file alone: no schema change,
no migration, no golden-spec churn.

Geometry is per profile. Caption Y in vertical is a different number from caption
Y in widescreen, and the box is expressed in normalized output coordinates so the
same spec produces a correctly placed caption in both.
"""

from __future__ import annotations

from spec.profiles import RenderProfile

from compile.timeline import EditedCaption

ASS_HEADER = """[Script Info]
; Generated by screencut compile. Do not edit; edit the spec and re-render.
ScriptType: v4.00+
PlayResX: {width}
PlayResY: {height}
WrapStyle: 2
ScaledBorderAndShadow: yes
YCbCr Matrix: TV.709

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Caption,{font},{size},&H00FFFFFF,&H000000FF,&H00101010,&HB4101010,-1,0,0,0,100,100,0,0,3,{pad},0,5,0,0,0,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""


def render_ass(captions: list[EditedCaption], profile: RenderProfile) -> str:
    """The whole subtitle file, as text. Deterministic — §11 hashes renders."""
    style = profile.captions
    size = max(int(round(style.type_scale * profile.height)), 8)
    # BorderStyle 3 draws an opaque box behind the text rather than an outline
    # around it, which is what keeps captions legible over a screen recording
    # where the background is arbitrary and often white.
    pad = max(int(round(size * 0.22)), 2)
    lines = [
        ASS_HEADER.format(
            width=profile.width,
            height=profile.height,
            font=style.font_family,
            size=size,
            pad=pad,
        )
    ]
    x = int(round((style.box.x + style.box.w / 2) * profile.width))
    y = int(round((style.box.y + style.box.h / 2) * profile.height))
    for caption in captions:
        text = wrap(caption.text, style.max_chars_per_line)
        lines.append(
            f"Dialogue: 0,{timestamp(caption.t_in)},{timestamp(caption.t_out)},"
            f"Caption,,0,0,0,,{{\\pos({x},{y})}}{text}\n"
        )
    return "".join(lines)


def wrap(text: str, max_chars: int) -> str:
    r"""Greedy wrap into ASS `\N` lines.

    Greedy rather than balanced on purpose: it is the rule a reader can predict
    from the caption itself, and `WrapStyle: 2` means libass does no wrapping of
    its own, so what this function decides is exactly what appears.
    """
    words = text.split()
    if not words:
        return ""
    lines: list[str] = []
    current = words[0]
    for word in words[1:]:
        if len(current) + 1 + len(word) <= max_chars:
            current = f"{current} {word}"
        else:
            lines.append(current)
            current = word
    lines.append(current)
    return "\\N".join(lines)


def timestamp(seconds: float) -> str:
    """ASS wants `H:MM:SS.cc`, and centisecond truncation is all the format has."""
    seconds = max(seconds, 0.0)
    hours, rest = divmod(int(seconds), 3600)
    minutes, secs = divmod(rest, 60)
    centis = int(round((seconds - int(seconds)) * 100))
    if centis == 100:  # rounding up a whole second must carry, not print ".100"
        centis = 0
        secs += 1
        if secs == 60:
            secs = 0
            minutes += 1
            if minutes == 60:
                minutes = 0
                hours += 1
    return f"{hours}:{minutes:02d}:{secs:02d}.{centis:02d}"


def line_count(caption: EditedCaption, profile: RenderProfile) -> int:
    return wrap(caption.text, profile.captions.max_chars_per_line).count("\\N") + 1
