"""JSON Schema -> TypeScript (decision #7).

The review UI (§8) edits the spec, so it needs the spec's types, and they must be
the *same* types — a hand-maintained TS mirror of a Pydantic model is a second
source of truth that goes stale exactly when a schema change matters.

Generated from the JSON Schema rather than from the models directly, so the TS
and the LLM prompts are provably reading the same document.

The emitted interfaces describe a **serialized** spec, where defaults have been
written out: every property is present, and only genuinely nullable ones are
`| null`.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from spec.origin import ORIGIN_KEY
from spec.schema import SCHEMA_DIR, SCHEMA_MODELS, combined_schema

HEADER = """// Generated by spec/tsgen.py from the Pydantic models. Do not edit.
// Regenerate with `make types`; `make check-generated` fails if this drifts.
//
// Every field carries the stage that produces it (architecture.md §11.1).
"""

_SCALARS = {
    "string": "string",
    "integer": "number",
    "number": "number",
    "boolean": "boolean",
    "null": "null",
}


def _ref_name(ref: str) -> str:
    return ref.rsplit("/", 1)[-1]


def ts_type(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return _ref_name(schema["$ref"])
    if "allOf" in schema and len(schema["allOf"]) == 1:
        return ts_type(schema["allOf"][0])
    if "anyOf" in schema:
        parts = [ts_type(s) for s in schema["anyOf"]]
        deduped = list(dict.fromkeys(parts))
        return " | ".join(deduped)
    if "const" in schema:
        return _literal(schema["const"])
    if "enum" in schema:
        return " | ".join(_literal(v) for v in schema["enum"])
    kind = schema.get("type")
    if kind == "array":
        items = schema.get("items")
        return f"{ts_type(items)}[]" if items else "unknown[]"
    if kind == "object":
        extra = schema.get("additionalProperties")
        if isinstance(extra, dict):
            return f"Record<string, {ts_type(extra)}>"
        return "Record<string, unknown>"
    if isinstance(kind, list):
        return " | ".join(_SCALARS.get(k, "unknown") for k in kind)
    return _SCALARS.get(kind, "unknown")


def _literal(value: Any) -> str:
    if isinstance(value, str):
        return f'"{value}"'
    if isinstance(value, bool):
        return "true" if value else "false"
    if value is None:
        return "null"
    return str(value)


def _doc(schema: dict[str, Any], indent: str) -> list[str]:
    description = schema.get("description")
    origin = schema.get(ORIGIN_KEY)
    if not description and not origin:
        return []
    lines = [f"{indent}/**"]
    if description:
        for line in _wrap(description, 84):
            lines.append(f"{indent} * {line}")
    if origin:
        if description:
            lines.append(f"{indent} *")
        lines.append(f"{indent} * @producedBy {origin['stage']} ({origin['origin']})")
    lines.append(f"{indent} */")
    return lines


def _wrap(text: str, width: int) -> list[str]:
    words, lines, current = text.split(), [], ""
    for word in words:
        candidate = f"{current} {word}".strip()
        if len(candidate) > width and current:
            lines.append(current)
            current = word
        else:
            current = candidate
    if current:
        lines.append(current)
    return lines


def _enum(name: str, schema: dict[str, Any]) -> str:
    out = _doc(schema, "")
    members = " | ".join(_literal(v) for v in schema["enum"])
    out.append(f"export type {name} = {members};")
    return "\n".join(out)


def _interface(name: str, schema: dict[str, Any]) -> str:
    out = _doc(schema, "")
    out.append(f"export interface {name} {{")
    for prop, prop_schema in schema.get("properties", {}).items():
        out.extend(_doc(prop_schema, "  "))
        out.append(f"  {prop}: {ts_type(prop_schema)};")
    out.append("}")
    return "\n".join(out)


def render_typescript() -> str:
    defs = combined_schema()["$defs"]
    blocks = [HEADER]
    roots = {m.__name__ for m in SCHEMA_MODELS.values()}
    for name in sorted(defs):
        schema = defs[name]
        if "enum" in schema:
            blocks.append(_enum(name, schema))
        else:
            blocks.append(_interface(name, schema))
    blocks.append(
        "/** Documents and fragments that are emitted as standalone schemas. */\n"
        "export type SpecDocument = " + " | ".join(sorted(roots)) + ";"
    )
    return "\n\n".join(blocks) + "\n"


def write_typescript(out_dir: Path = SCHEMA_DIR) -> Path:
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / "screencut.ts"
    path.write_text(render_typescript())
    return path


if __name__ == "__main__":
    print(write_typescript())
