// Generated by spec/tsgen.py from the Pydantic models. Do not edit.
// Regenerate with `make types`; `make check-generated` fails if this drifts.
//
// Every field carries the stage that produces it (architecture.md §11.1).


/**
 * Narration and an optional bed, with the loudness targets §9.1 checks against.
 */
export interface AudioTrack {
  /**
   * @producedBy audio (deterministic)
   */
  narration_gain_db: number;
  /**
   * Bed, relative to the job directory. A licensed track is a source like any other
   * (§15).
   *
   * @producedBy config (deterministic)
   */
  music_path: string | null;
  /**
   * @producedBy audio (deterministic)
   */
  music_gain_db: number;
  /**
   * How far the bed drops under narration. Negative.
   *
   * @producedBy audio (deterministic)
   */
  duck_db: number;
  /**
   * @producedBy config (deterministic)
   */
  target_lufs: number;
  /**
   * @producedBy config (deterministic)
   */
  true_peak_ceiling_dbtp: number;
}

/**
 * A displayed block, in source time, with the words that make it up.
 */
export interface CaptionBlock {
  /**
   * @producedBy plan_captions (deterministic)
   */
  t_in: number;
  /**
   * @producedBy plan_captions (deterministic)
   */
  t_out: number;
  /**
   * Words in this block, ascending. Never empty in practice; empty is rejected.
   *
   * @producedBy plan_captions (deterministic)
   */
  words: Word[];
}

/**
 * Caption box geometry and type scale, in output-normalized coordinates. Learned per
 * profile (§4.1) — this is the example that argues for two layers.
 */
export interface CaptionStyle {
  /**
   * Where the caption block sits in the output frame.
   *
   * @producedBy config (deterministic)
   */
  box: Rect;
  /**
   * @producedBy config (deterministic)
   */
  font_family: string;
  /**
   * Cap height as a fraction of output height.
   *
   * @producedBy config (deterministic)
   */
  type_scale: number;
  /**
   * @producedBy config (deterministic)
   */
  max_chars_per_line: number;
  /**
   * @producedBy config (deterministic)
   */
  max_lines: number;
  /**
   * @producedBy config (deterministic)
   */
  min_display_s: number;
}

/**
 * `removals` + `segments`, partitioning the source exactly. Validated here: in
 * ascending order, non-inverted, non-overlapping, contiguous, and starting at 0.0. The
 * one thing that cannot be checked here is where the partition *ends* — that needs the
 * source duration, so `EditSpec` checks it (§4.4's totality is a two-model invariant
 * only because duration lives on the source).
 */
export interface EditDecisions {
  /**
   * @producedBy plan_edit (model)
   */
  removals: Removal[];
  /**
   * @producedBy plan_edit (model)
   */
  segments: Segment[];
}

export interface EditSpec {
  /**
   * Carried from the first commit (§4.2). Load through `spec.migrations.load_spec`,
   * never bare.
   *
   * @producedBy system (deterministic)
   */
  spec_version: number;
  /**
   * @producedBy system (deterministic)
   */
  job_id: string;
  /**
   * @producedBy system (deterministic)
   */
  created_at: string;
  /**
   * @producedBy ingest (deterministic)
   */
  source: Source;
  /**
   * @producedBy config (deterministic)
   */
  narration: Narration;
  /**
   * @producedBy ingest (deterministic)
   */
  focus: FocusTrack;
  /**
   * @producedBy plan_edit (model)
   */
  edit: EditDecisions;
  /**
   * @producedBy plan_captions (deterministic)
   */
  captions: CaptionBlock[];
  /**
   * @producedBy plan_overlays (model)
   */
  overlays: OverlayIntent[];
  /**
   * @producedBy audio (deterministic)
   */
  audio: AudioTrack;
}

/**
 * Encode settings for both paths, because both are used. Quality is expressed twice on
 * purpose. `crf` and `preset` are x264's scales and govern the software path;
 * `quality` is VideoToolbox's and governs the hardware one. They are not convertible,
 * so a single knob would have to lie about one encoder — and on the target machine
 * (§16) the hardware encoder is the default, which is the path a lone `crf` would
 * silently fail to control. `compile` reads whichever pair matches `encoder`.
 */
export interface EncodeSettings {
  /**
   * @producedBy config (deterministic)
   */
  encoder: Encoder;
  /**
   * @producedBy config (deterministic)
   */
  video_codec: string;
  /**
   * Software path only (x264): lower is better.
   *
   * @producedBy config (deterministic)
   */
  crf: number;
  /**
   * Software path only (x264).
   *
   * @producedBy config (deterministic)
   */
  preset: string;
  /**
   * Hardware path only (VideoToolbox `-q:v`): higher is better. Phase 2 confirms the
   * range against the installed FFmpeg before relying on it.
   *
   * @producedBy config (deterministic)
   */
  quality: number;
  /**
   * @producedBy config (deterministic)
   */
  pix_fmt: string;
  /**
   * @producedBy config (deterministic)
   */
  audio_codec: string;
  /**
   * @producedBy config (deterministic)
   */
  audio_bitrate_kbps: number;
}

export type Encoder = "videotoolbox" | "software";

/**
 * Why attention is at this point, which decides how much it counts for.
 */
export type FocusKind = "movement" | "click" | "dwell" | "manual";

export type FocusMode = "zoom_keyframes" | "crop_path";

export interface FocusPoint {
  /**
   * Source time in seconds.
   *
   * @producedBy ingest (deterministic)
   */
  t: number;
  /**
   * @producedBy ingest (deterministic)
   */
  x: number;
  /**
   * @producedBy ingest (deterministic)
   */
  y: number;
  /**
   * How strongly this point attracts framing. Clicks outweigh movement.
   *
   * @producedBy ingest (deterministic)
   */
  weight: number;
  /**
   * @producedBy ingest (deterministic)
   */
  kind: FocusKind;
}

/**
 * The §4.3 tunables. Every one is a scalar the preference store learns by median, and
 * every one is a number you can also just set by hand when a job needs it.
 */
export interface FocusProjection {
  /**
   * @producedBy config (deterministic)
   */
  mode: FocusMode;
  /**
   * Magnification at a dwell region in zoom mode. In crop mode it tightens the constant
   * window beyond the aspect fit, and 1.0 is the honest default there — cropping 9:16
   * out of 16:9 already costs a 1.8x upscale.
   *
   * @producedBy config (deterministic)
   */
  zoom_factor: number;
  /**
   * @producedBy config (deterministic)
   */
  min_dwell_ms: number;
  /**
   * @producedBy config (deterministic)
   */
  min_gap_ms: number;
  /**
   * @producedBy config (deterministic)
   */
  ease_ms: number;
  /**
   * @producedBy config (deterministic)
   */
  crop_lag_ms: number;
  /**
   * Normalized crop movement ceiling. Judder is *the* failure mode of automated
   * reframing (§9.1).
   *
   * @producedBy config (deterministic)
   */
  max_crop_delta_per_frame: number;
}

export interface FocusTrack {
  /**
   * Sampled attention, ascending in t. May be empty — a still with no manual point.
   *
   * @producedBy ingest (deterministic)
   */
  points: FocusPoint[];
}

export interface Narration {
  /**
   * @producedBy config (deterministic)
   */
  source: NarrationSource;
  /**
   * Supplied or AI-drafted (decision #8). Null when narration is whatever you said on
   * the take.
   *
   * @producedBy script_draft (model)
   */
  script: string | null;
  /**
   * Per-job reference audio, relative to the job directory. Required to synthesize.
   *
   * @producedBy config (deterministic)
   */
  voice_reference_path: string | null;
  /**
   * Recorded on the job so the boundary of decision #20 is auditable, not assumed.
   *
   * @producedBy human (deterministic)
   */
  voice_consent_note: string | null;
}

export type NarrationSource = "recorded" | "synthesized";

/**
 * One overlay, anchored in source time and normalized source space. `t_in`/`t_out` are
 * both null for an overlay that spans the whole output — the progress pill is the
 * case. That is not a second time base (§4.5): an element spanning the whole output
 * needs no anchor at all, so compile runs it from zero to the end of whatever it
 * produced. Anything positioned at a *moment* is positioned relative to content, which
 * is a source-time anchor like any other, and compile drops it if the moment lands
 * inside a removal.
 */
export interface OverlayIntent {
  /**
   * @producedBy plan_overlays (model)
   */
  template: OverlayTemplate;
  /**
   * @producedBy plan_overlays (model)
   */
  text: string;
  /**
   * Normalized source position. Null for a whole-output overlay, which has nothing to
   * point at.
   *
   * @producedBy plan_overlays (model)
   */
  anchor: Point | null;
  /**
   * @producedBy plan_overlays (model)
   */
  t_in: number | null;
  /**
   * @producedBy plan_overlays (model)
   */
  t_out: number | null;
}

/**
 * The fragment `plan_overlays` returns (§7.2). Small and heavily typed on purpose:
 * normalized coordinates and enum template names mean most wrong answers are *invalid*
 * answers, which is risk R5's real mitigation.
 */
export interface OverlayPlan {
  /**
   * @producedBy plan_overlays (model)
   */
  overlays: OverlayIntent[];
}

/**
 * The closed set. Adding one is a template plus a `spec_version` bump.
 */
export type OverlayTemplate = "callout_arrow" | "highlight_box" | "label_chip" | "progress_pill";

/**
 * A position in normalized source coordinates.
 */
export interface Point {
  x: number;
  y: number;
}

/**
 * A rectangle in normalized coordinates, origin top-left.
 */
export interface Rect {
  x: number;
  y: number;
  w: number;
  h: number;
}

/**
 * A range that never survives, in any profile. Expressed as a range rather than as
 * rewritten text, and that is what keeps this an edit: audio and caption are cut at
 * the same instants, from the same decision, and nothing is put into your mouth that
 * you did not say.
 */
export interface Removal {
  /**
   * @producedBy plan_edit (model)
   */
  t_in: number;
  /**
   * @producedBy plan_edit (model)
   */
  t_out: number;
  /**
   * @producedBy plan_edit (model)
   */
  kind: RemovalKind;
  /**
   * Which stage first proposed this range. `trim` for an arithmetic proposal the model
   * kept, `plan_edit` for one the model added. Feeds the trim override rate on the
   * verification report (§9.1).
   *
   * @producedBy plan_edit (model)
   */
  proposed_by: "trim" | "plan_edit";
}

/**
 * Why a range does not survive. Silence and filler are `trim`'s to find (§4.6,
 * arithmetic); false starts and redundancy are `plan_edit`'s (language).
 */
export type RemovalKind = "silence" | "filler" | "false_start" | "redundant";

export interface RenderProfile {
  /**
   * @producedBy config (deterministic)
   */
  name: string;
  /**
   * @producedBy config (deterministic)
   */
  width: number;
  /**
   * @producedBy config (deterministic)
   */
  height: number;
  /**
   * @producedBy config (deterministic)
   */
  fps: number;
  /**
   * Seconds this profile is willing to run. Decides how aggressively it cuts, and it is
   * one scalar rather than a cut list — which is what makes cuts aspect-agnostic
   * (§4.4.1) and cut pacing learnable (§10).
   *
   * @producedBy config (deterministic)
   */
  duration_budget: number;
  /**
   * @producedBy config (deterministic)
   */
  safe_area: SafeArea;
  /**
   * @producedBy config (deterministic)
   */
  captions: CaptionStyle;
  /**
   * @producedBy config (deterministic)
   */
  focus: FocusProjection;
  /**
   * @producedBy config (deterministic)
   */
  encode: EncodeSettings;
}

/**
 * Insets as fractions of the output. Captions and overlays live inside it (§9.1).
 */
export interface SafeArea {
  /**
   * @producedBy config (deterministic)
   */
  top: number;
  /**
   * @producedBy config (deterministic)
   */
  right: number;
  /**
   * @producedBy config (deterministic)
   */
  bottom: number;
  /**
   * @producedBy config (deterministic)
   */
  left: number;
}

/**
 * Surviving content, ranked. `reason` is what makes a tier reviewable.
 */
export interface Segment {
  /**
   * @producedBy plan_edit (model)
   */
  t_in: number;
  /**
   * @producedBy plan_edit (model)
   */
  t_out: number;
  /**
   * @producedBy plan_edit (model)
   */
  tier: Tier;
  /**
   * Why this segment got this tier. Shown in review (§8); a tier with no reason cannot
   * be argued with.
   *
   * @producedBy plan_edit (model)
   */
  reason: string;
}

/**
 * A single raw take, plus the facts about it the compiler needs. One source per job,
 * singular and deliberate. Multi-take assembly is a schema field *and* a compiler
 * change (decision #24); §4.2's migration registry is what makes adding it later
 * ordinary rather than alarming. `path` is relative to the job directory, never
 * absolute: a job directory has to survive being moved or archived into `golden/`.
 */
export interface Source {
  /**
   * Stable id of the take within the job.
   *
   * @producedBy ingest (deterministic)
   */
  source_id: string;
  /**
   * Media path, relative to the job directory.
   *
   * @producedBy ingest (deterministic)
   */
  path: string;
  /**
   * Recorder event sidecar, relative to the job directory. None when the recorder
   * produced none.
   *
   * @producedBy ingest (deterministic)
   */
  events_path: string | null;
  /**
   * Source duration in seconds.
   *
   * @producedBy ingest (deterministic)
   */
  duration: number;
  /**
   * @producedBy ingest (deterministic)
   */
  width: number;
  /**
   * @producedBy ingest (deterministic)
   */
  height: number;
  /**
   * @producedBy ingest (deterministic)
   */
  fps: number;
  /**
   * @producedBy ingest (deterministic)
   */
  has_audio: boolean;
}

/**
 * How good a segment is — aspect-independent taste, decided once (§4.4.1). Which tiers
 * survive is a *separate*, per-profile, arithmetic decision driven by
 * `duration_budget`. Tiers are a ranking, not a cut.
 */
export type Tier = "essential" | "supporting" | "optional";

/**
 * One spoken word with its alignment window. `emphasis` is the only model-written
 * field in the caption subtree (§7.1: emphasis selection is taste, timing and layout
 * are not) — which is exactly the mixed-origin case §11.1's per-field metadata exists
 * for.
 */
export interface Word {
  /**
   * @producedBy align (deterministic)
   */
  t_in: number;
  /**
   * @producedBy align (deterministic)
   */
  t_out: number;
  /**
   * @producedBy align (deterministic)
   */
  text: string;
  /**
   * @producedBy emphasis (model)
   */
  emphasis: boolean;
}

/** Documents and fragments that are emitted as standalone schemas. */
export type SpecDocument = EditDecisions | EditSpec | OverlayPlan | RenderProfile;
